spring:
  profiles:
    active: test
    group:
      prod: real-db
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
hosting-file:
  server:
    path: C:\\Users\\joel6\\Desktop\\
  url:
    path: http://localhost:8080/
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
hosting-file:
  server:
    path: /home/ubuntu/userfile/
  url:
    path: https://easy-deploy.kr/
---
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
spring:
  web:
    resources:
      static-locations: classpath:/static, file:/static
      cache:
        cachecontrol:
          cache-public: true
          must-revalidate: true
          max-age: 86400
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
slack:
  url: slackUrl
server:
  compression:
    enabled: true
